from __future__ import annotations

import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check_repository_policy.py"
SPEC = importlib.util.spec_from_file_location("check_repository_policy", SCRIPT)
assert SPEC and SPEC.loader
policy = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = policy
SPEC.loader.exec_module(policy)


class RepositoryPolicyTests(unittest.TestCase):
    def test_maintained_bilingual_contract(self) -> None:
        self.assertEqual([], policy.check_bilingual_contract(ROOT))

    def test_ci_boundaries(self) -> None:
        self.assertEqual([], policy.check_ci_contract(ROOT))

    def test_idf_partition_contract(self) -> None:
        self.assertEqual([], policy.check_idf_partition_contract(ROOT))

    def test_idf_component_names_cover_both_supported_lines(self) -> None:
        i2c_cmake = (ROOT / "examples/esp-idf/i2c-tools/main/CMakeLists.txt").read_text(
            encoding="utf-8"
        )
        lcd_cmake = (ROOT / "examples/esp-idf/lcd-color-test/CMakeLists.txt").read_text(
            encoding="utf-8"
        )
        usb_cmake = (
            ROOT / "examples/esp-idf/usb-extended-screen/main/CMakeLists.txt"
        ).read_text(encoding="utf-8")
        self.assertIn("REQUIRES console ", i2c_cmake)
        self.assertNotIn("tools/unit-test-app/components", lcd_cmake)
        self.assertIn("espressif__usb_device_uac", usb_cmake)

    def test_arduino_autogenerated_prototypes_have_matching_attributes(self) -> None:
        for relative in (
            "examples/arduino/GFX_ESPWiFiAnalyzer/GFX_ESPWiFiAnalyzer.ino",
            "examples/arduino/LVGLV9_Arduino/LVGLV9_Arduino.ino",
        ):
            self.assertNotIn("[[noreturn]]", (ROOT / relative).read_text(encoding="utf-8"))

    def test_lvgl_and_usb_compatibility_contract(self) -> None:
        lvgl_projects = ("display-panel", "lvgl-v8", "lvgl-v9", "usb-extended-screen")
        for project in lvgl_projects:
            manifest = (
                ROOT / f"examples/esp-idf/{project}/main/idf_component.yml"
            ).read_text(encoding="utf-8")
            self.assertIn('espressif/esp_lvgl_adapter:\n    version: "0.6.3"', manifest)

        lvgl9_projects = ("display-panel", "lvgl-v9", "usb-extended-screen")
        for project in lvgl9_projects:
            manifest = (
                ROOT / f"examples/esp-idf/{project}/main/idf_component.yml"
            ).read_text(encoding="utf-8")
            defaults = (ROOT / f"examples/esp-idf/{project}/sdkconfig.defaults").read_text(
                encoding="utf-8"
            )
            self.assertIn('lvgl/lvgl:\n    version: "9.3.0"', manifest)
            self.assertIn("CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM=n", defaults)
            self.assertNotIn("CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM=y", defaults)

        lvgl_v8_cmake = (ROOT / "examples/esp-idf/lvgl-v8/CMakeLists.txt").read_text(
            encoding="utf-8"
        )
        self.assertIn("lv_disp_rotation_t=lv_disp_rot_t", lvgl_v8_cmake)

        usb_defaults = (
            ROOT / "examples/esp-idf/usb-extended-screen/sdkconfig.defaults"
        ).read_text(encoding="utf-8")
        self.assertIn("CONFIG_USB_DEVICE_UAC_AS_PART=y", usb_defaults)

    def test_exact_policy_cli(self) -> None:
        completed = subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(ROOT)],
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
        self.assertEqual(0, completed.returncode, completed.stderr)
        self.assertIn("Repository policy:", completed.stdout)


if __name__ == "__main__":
    unittest.main()
