[CmdletBinding()]
param([string]$Port = '', [switch]$ListOnly, [switch]$SelfTest)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Repo = 'waveshareteam/ESP32-P4-WIFI6-Touch-LCD-4B'
$Board = 'ESP32-P4-WIFI6-Touch-LCD-4B'
$FlashLimit = 32MB
$DefaultStartIndex = 1
$Items = @(
    'audio-codec','display-panel','ethernet','hello_world','i2c-tools','lcd-color-test','lvgl-v8','lvgl-v9','project-template','rs485','sd-card','usb-extended-screen','wifi-station' | ForEach-Object {
        $name = $_
        foreach ($version in @('v5.5.5','v6.0.2')) {
            [pscustomobject]@{ Workflow='esp-idf.yml'; Artifact="firmware-esp-idf-$name-$version"; Framework='esp-idf'; Version=$version; SourceProject="examples/esp-idf/$name" }
        }
    }
)
$Items += @('AsciiTable','Drawing_board','GFX_ESPWiFiAnalyzer','HelloWorld','LVGLV9_Arduino' | ForEach-Object { [pscustomobject]@{ Workflow='arduino.yml'; Artifact="firmware-arduino-$($_)-3.3.11"; Framework='arduino-esp32'; Version='3.3.11'; SourceProject="examples/arduino/$_" } })
$Items += [pscustomobject]@{ Workflow='firmware.yml'; Artifact='firmware-brookesia-v5.5.5'; Framework='esp-idf'; Version='v5.5.5'; SourceProject='firmware/brookesia' }
for ($index = 0; $index -lt $Items.Count; ++$index) { $Items[$index] | Add-Member -NotePropertyName Index -NotePropertyValue ($index + 1) }

function Test-Port([string]$Value) { return $Value -match '^COM\d+$' }
function Test-RelativePackagePath([string]$Root, [string]$Relative) { if ([string]::IsNullOrWhiteSpace($Relative) -or [IO.Path]::IsPathRooted($Relative)) { return $false }; $prefix = [IO.Path]::GetFullPath($Root).TrimEnd('\','/') + [IO.Path]::DirectorySeparatorChar; return [IO.Path]::GetFullPath((Join-Path $Root $Relative)).StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase) }
function Get-FileSha256([string]$Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Test-FlashCommand([string]$Command) { return -not [string]::IsNullOrWhiteSpace($Command) -and $Command -match '^python\s+-m\s+esptool\s+--chip\s+esp32p4\s+--baud\s+460800\s+write_flash\s+' -and $Command -notmatch '(?i)(erase|read_flash|write_reg|run|execute|reset)' }
function Test-ArduinoFqbn([string]$Value) { $parts=$Value -split ':',4; if($parts.Count -ne 4 -or $parts[0] -ne 'esp32' -or $parts[1] -ne 'esp32' -or $parts[2] -ne 'esp32p4'){return $false}; $options=@{}; foreach($entry in ($parts[3] -split ',')){ $pair=$entry -split '=',2; if($pair.Count -ne 2 -or [string]::IsNullOrWhiteSpace($pair[0]) -or [string]::IsNullOrWhiteSpace($pair[1]) -or $options.ContainsKey($pair[0])){return $false}; $options[$pair[0]]=$pair[1] }; return $options['FlashSize'] -ceq '32M' -and $options['ChipVariant'] -ceq 'prev3' -and $options['EraseFlash'] -ceq 'none' }
function Get-NextProgress([int]$Current, [int[]]$Confirmed) { $all = @($Confirmed + $Current | Where-Object { $_ -ge 1 -and $_ -le $Items.Count } | Sort-Object -Unique); return [pscustomobject]@{ CurrentIndex = if ($Current -lt $Items.Count) { $Current + 1 } else { $Current }; ConfirmedIndexes = $all; Completed = $Current -eq $Items.Count } }
function Get-StateForFinalSha($Saved, [string]$FinalSha, [string]$DefaultPort) { if (-not $Saved -or -not $Saved.PSObject.Properties['FinalSha'] -or -not $Saved.PSObject.Properties['CurrentIndex'] -or -not $Saved.PSObject.Properties['ConfirmedIndexes'] -or [string]$Saved.FinalSha -ne $FinalSha) { return [pscustomobject]@{ CurrentIndex=$DefaultStartIndex; ConfirmedIndexes=@(); Port=$DefaultPort } }; $current = [int]$Saved.CurrentIndex; if ($current -lt 1 -or $current -gt $Items.Count) { throw 'Saved progress is outside the 32-item range.' }; return [pscustomobject]@{ CurrentIndex=$current; ConfirmedIndexes=@($Saved.ConfirmedIndexes | ForEach-Object {[int]$_} | Where-Object {$_ -ge 1 -and $_ -le $Items.Count} | Sort-Object -Unique); Port=$DefaultPort } }
function Resolve-Executable([string]$Name, [string[]]$Fallbacks) { $command = Get-Command $Name -ErrorAction SilentlyContinue | Select-Object -First 1; if ($command -and $command.Source) { return $command.Source }; foreach ($candidate in $Fallbacks) { if (Test-Path -LiteralPath $candidate -PathType Leaf) { return $candidate } }; throw "$Name was not found." }
function Resolve-Git { return Resolve-Executable 'git' @((Join-Path ${env:ProgramFiles} 'Git\cmd\git.exe'), 'C:\Git\cmd\git.exe') }
function Resolve-Gh { return Resolve-Executable 'gh' @((Join-Path ${env:ProgramFiles} 'GitHub CLI\gh.exe')) }
function Resolve-PythonWithEsptool { $candidates=@(); foreach($name in @('python','py')){$command=Get-Command $name -ErrorAction SilentlyContinue|Select-Object -First 1;if($command -and $command.Source){$candidates+=$command.Source}}; foreach ($candidate in @($candidates | Select-Object -Unique)) { & $candidate -c 'import esptool' *> $null; if ($LASTEXITCODE -eq 0) { return $candidate } }; throw 'No Python interpreter with esptool was found.' }
function Resolve-DefaultPort { $known = @(Get-CimInstance Win32_PnPEntity -ErrorAction SilentlyContinue | Where-Object { $_.Name -match '(?i)(CH343|ESP32-P4)' -and $_.Name -match '\(COM\d+\)' } | ForEach-Object { [regex]::Match($_.Name, '\((COM\d+)\)').Groups[1].Value } | Sort-Object -Unique); if ($known.Count -eq 1) { return $known[0] }; throw 'Unable to identify exactly one explicitly named CH343 or ESP32-P4 serial port; pass -Port COMx.' }
function Invoke-EsptoolProbe([string]$Python, [string]$SelectedPort) { $output = (& $Python -m esptool --chip esp32p4 --port $SelectedPort chip_id 2>&1 | Out-String); if ($LASTEXITCODE -ne 0) { $output = (& $Python -m esptool --chip esp32p4 --port $SelectedPort chip-id 2>&1 | Out-String) }; $revision=[regex]::Match($output,'(?i)(revision|rev)[^0-9]*([0-9]+)'); if ($LASTEXITCODE -ne 0 -or $output -notmatch 'ESP32-P4' -or -not $revision.Success) { throw 'Port probe did not prove an ESP32-P4 with a parsable revision.' }; if ([int]$revision.Groups[2].Value -ge 3) { throw 'This repository CI firmware board-profile policy supports only pre-v3 ESP32-P4 revisions.' } }
function Resolve-FinalSha([string]$Git) { $sha = (& $Git -C $RepoRoot rev-parse HEAD 2>&1 | Out-String).Trim(); if ($LASTEXITCODE -ne 0 -or $sha -notmatch '^[0-9a-fA-F]{40}$') { throw 'Unable to resolve a full local HEAD SHA.' }; return $sha.ToLowerInvariant() }
function Assert-ReadySource([string]$Git) { $status = (& $Git -C $RepoRoot status --porcelain=v1 --untracked-files=all 2>&1 | Out-String); if ($LASTEXITCODE -ne 0 -or -not [string]::IsNullOrWhiteSpace($status)) { throw 'Refusing to continue: the working tree must be clean.' }; $branch = (& $Git -C $RepoRoot symbolic-ref --quiet --short HEAD 2>&1 | Out-String).Trim(); if ($LASTEXITCODE -ne 0 -or -not $branch) { throw 'Refusing to continue: check out a non-detached branch first.' }; return $branch }
function Assert-ReadyPullRequest([string]$Gh, [string]$Branch, [string]$Sha) { $raw = (& $Gh pr list --repo $Repo --head $Branch --state open --limit 2 --json number,state,isDraft,headRefName,headRefOid 2>&1 | Out-String); if ($LASTEXITCODE -ne 0) { throw 'Unable to query the current pull request.' }; $prs = @($raw | ConvertFrom-Json); if ($prs.Count -ne 1 -or $prs[0].isDraft -or $prs[0].headRefName -ne $Branch -or $prs[0].headRefOid -ne $Sha) { throw 'Exactly one open non-draft pull request at the complete local HEAD is required.' } }
function Resolve-ArtifactRuns([string]$Gh, [string]$Sha) { $runs=@{}; foreach ($workflow in @($Items.Workflow | Sort-Object -Unique)) { $raw = (& $Gh run list --repo $Repo --workflow $workflow --commit $Sha --status success --limit 20 --json databaseId,headSha,createdAt 2>&1 | Out-String); if ($LASTEXITCODE -ne 0) { throw "Unable to list successful $workflow runs." }; $found=@($raw | ConvertFrom-Json | Where-Object {$_.headSha -eq $Sha} | Sort-Object createdAt -Descending); if ($found.Count -lt 1) { throw "No successful $workflow run exists for local HEAD $Sha." }; $runs[$workflow]=[string]$found[0].databaseId }; foreach ($item in $Items) { $item | Add-Member -Force -NotePropertyName Run -NotePropertyValue $runs[$item.Workflow] } }
function New-RunPaths { foreach ($path in @($StateRoot, $DownloadRoot, $LogRoot)) { if (-not (Test-Path -LiteralPath $path)) { New-Item -ItemType Directory -Path $path | Out-Null } }; $stamp=Get-Date -Format 'yyyyMMdd-HHmmss-fff'; $download=Join-Path $DownloadRoot $stamp; $log=Join-Path $LogRoot "$stamp.log"; if ((Test-Path $download) -or (Test-Path $log)) { throw 'Refusing to overwrite an existing log or download directory.' }; New-Item -ItemType Directory -Path $download | Out-Null; New-Item -ItemType File -Path $log | Out-Null; return [pscustomobject]@{ DownloadDir=$download; LogPath=$log } }
function Test-PackageManifest([string]$PackageDir, $Item, [string]$Sha) { $manifestPath=Join-Path $PackageDir 'manifest.json'; $manifest=Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json; if ($manifest.schema_version -ne 1 -or $manifest.board -ne $Board -or $manifest.chip -ne 'esp32p4' -or $manifest.board_profile -ne 'pre-v3' -or [bool]$manifest.c6_firmware_included -or $manifest.framework -ne $Item.Framework -or $manifest.framework_version -ne $Item.Version -or $manifest.source_project -ne $Item.SourceProject -or $manifest.git_sha -ne $Sha -or $manifest.flash.size_bytes -ne $FlashLimit -or $manifest.flash.baud -ne 460800 -or -not (Test-FlashCommand ([string]$manifest.flash.command))) { throw 'Package manifest identity or flash command is not safe for the selected item.' }; if($Item.Framework -eq 'arduino-esp32' -and -not (Test-ArduinoFqbn ([string]$manifest.fqbn))){throw 'Arduino package FQBN is not the exact required ESP32-P4 board profile.'}; $plan=@(); foreach ($file in @($manifest.files)) { $relative=[string]$file.archive_path; if (-not (Test-RelativePackagePath $PackageDir $relative) -or [string]$file.sha256 -notmatch '^[0-9a-fA-F]{64}$' -or [int64]$file.size -le 0 -or [string]$file.offset -notmatch '^0x[0-9a-fA-F]+$') { throw 'Manifest contains unsafe flash metadata.' }; $path=Join-Path $PackageDir $relative; if (-not (Test-Path $path -PathType Leaf) -or (Get-FileSha256 $path) -ne [string]$file.sha256 -or [int64](Get-Item $path).Length -ne [int64]$file.size) { throw 'Manifest checksum or size verification failed.' }; $plan += [pscustomobject]@{ Offset=[Convert]::ToInt64($file.offset.Substring(2),16); Size=[int64]$file.size; Path=$path } }; $ordered=@($plan | Sort-Object Offset); if ($ordered.Count -lt 1) { throw 'Package contains no flashable files.' }; for ($index=0; $index -lt $ordered.Count; ++$index) { if ($ordered[$index].Offset + $ordered[$index].Size -gt $FlashLimit -or ($index -gt 0 -and $ordered[$index-1].Offset + $ordered[$index-1].Size -gt $ordered[$index].Offset)) { throw 'Package contains overlapping or out-of-range flash data.' } }; return $ordered }
function Invoke-CurrentFlash($Item, [string]$SelectedPort, [string]$Gh, [string]$Python, [string]$Sha) { Invoke-EsptoolProbe $Python $SelectedPort; $paths=New-RunPaths; $download=(& $Gh run download $Item.Run --repo $Repo --name $Item.Artifact --dir $paths.DownloadDir 2>&1 | Out-String); $downloadExit=$LASTEXITCODE; Add-Content -LiteralPath $paths.LogPath -Value $download; if ($downloadExit -ne 0) { throw "Artifact download failed; log: $($paths.LogPath)" }; foreach($zip in @(Get-ChildItem -LiteralPath $paths.DownloadDir -Recurse -Filter '*.zip' -File)){$destination=Join-Path $zip.DirectoryName ($zip.BaseName + '-unzipped');if(Test-Path $destination){throw 'Refusing to overwrite artifact extraction directory.'};Expand-Archive -LiteralPath $zip.FullName -DestinationPath $destination}; $manifests=@(Get-ChildItem -LiteralPath $paths.DownloadDir -Recurse -Filter manifest.json -File); if ($manifests.Count -ne 1) { throw 'Downloaded artifact must contain exactly one manifest.json.' }; $plan=Test-PackageManifest $manifests[0].DirectoryName $Item $Sha; $arguments=@('-m','esptool','--port',$SelectedPort,'--chip','esp32p4','--baud','460800','write_flash'); foreach ($entry in $plan) { $arguments += ('0x{0:X}' -f $entry.Offset); $arguments += $entry.Path }; $output=(& $Python @arguments 2>&1 | Out-String); Add-Content -LiteralPath $paths.LogPath -Value $output; return [pscustomobject]@{ Success=($LASTEXITCODE -eq 0 -and $output.Contains('Hash of data verified')); Output=$output; LogPath=$paths.LogPath } }

if ($SelfTest) { if ($Items.Count -ne 32 -or (Test-RelativePackagePath 'C:\package' '..\escape.bin') -or -not (Test-RelativePackagePath 'C:\package' 'bin\app.bin')) { throw 'Self-test safety contract failed.' }; $reset=Get-StateForFinalSha ([pscustomobject]@{FinalSha='old';CurrentIndex=3;ConfirmedIndexes=@(1)}) 'new' ''; $incomplete=Get-StateForFinalSha ([pscustomobject]@{FinalSha='expected'}) 'expected' ''; if ($reset.CurrentIndex -ne 1 -or $incomplete.CurrentIndex -ne 1 -or @($incomplete.ConfirmedIndexes).Count -ne 0) { throw 'Self-test state reset failed.' }; Write-Output 'SELF_TEST_OK items=32 state-reset=ok safe-paths=ok'; return }
if ($ListOnly) { Write-Output 'finalSHA=resolved-at-runtime'; Write-Output 'defaultPort=auto-detect-at-runtime'; Write-Output 'C6FirmwareIncluded=false'; foreach ($item in $Items) { Write-Output ('{0}: workflow={1} artifact={2} source={3}' -f $item.Index,$item.Workflow,$item.Artifact,$item.SourceProject) }; return }

$RepoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')); $StateRoot=Join-Path $env:LOCALAPPDATA 'Waveshare\ESP32-P4-WIFI6-Touch-LCD-4B\ci-firmware'; $DownloadRoot=Join-Path $StateRoot 'downloads'; $LogRoot=Join-Path $StateRoot 'logs'; $StatePath=Join-Path $StateRoot 'state-v1.json'
$Git=Resolve-Git; $Sha=Resolve-FinalSha $Git; $Branch=Assert-ReadySource $Git; $Gh=Resolve-Gh; Assert-ReadyPullRequest $Gh $Branch $Sha; $Python=Resolve-PythonWithEsptool; if (-not $Port) { $Port=Resolve-DefaultPort }; $Port=$Port.Trim().ToUpperInvariant(); if (-not (Test-Port $Port)) { throw 'Port must be COM followed by digits.' }; Resolve-ArtifactRuns $Gh $Sha
Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing
$saved=if(Test-Path $StatePath){Get-Content $StatePath -Raw|ConvertFrom-Json}else{$null}; $state=Get-StateForFinalSha $saved $Sha $Port; $script:CurrentIndex=$state.CurrentIndex; $script:Confirmed=@($state.ConfirmedIndexes); $script:FlashVerified=$false
function Save-State { [pscustomobject]@{FinalSha=$Sha;CurrentIndex=$script:CurrentIndex;ConfirmedIndexes=$script:Confirmed;Port=$portBox.Text.Trim().ToUpperInvariant();UpdatedAt=(Get-Date).ToString('o')}|ConvertTo-Json|Set-Content -LiteralPath $StatePath -Encoding utf8 }
$form=New-Object Windows.Forms.Form; $form.Text='CI Firmware Flasher'; $form.StartPosition='CenterScreen'; $form.ClientSize=New-Object Drawing.Size(820,620); $form.FormBorderStyle='FixedDialog'; $form.MaximizeBox=$false
function Add-Label($text,$x,$y,$width=780){$label=New-Object Windows.Forms.Label;$label.Text=$text;$label.Location=New-Object Drawing.Point($x,$y);$label.Size=New-Object Drawing.Size($width,20);$form.Controls.Add($label);return $label}
[void](Add-Label "Repository: $Repo" 15 15); [void](Add-Label "Final SHA: $Sha" 15 40); [void](Add-Label 'Port:' 15 70 45); $portBox=New-Object Windows.Forms.TextBox;$portBox.Text=$state.Port;$portBox.Location=New-Object Drawing.Point(65,67);$form.Controls.Add($portBox);$current=Add-Label '' 15 100;$status=Add-Label 'Status: flash current item, then perform the manual runtime test.' 15 125
$list=New-Object Windows.Forms.ListBox;$list.Font=New-Object Drawing.Font('Consolas',9);$list.Location=New-Object Drawing.Point(15,155);$list.Size=New-Object Drawing.Size(790,250);$form.Controls.Add($list);$output=New-Object Windows.Forms.TextBox;$output.Multiline=$true;$output.ReadOnly=$true;$output.ScrollBars='Both';$output.Location=New-Object Drawing.Point(15,415);$output.Size=New-Object Drawing.Size(790,135);$form.Controls.Add($output)
$flash=New-Object Windows.Forms.Button;$flash.Text='Flash current';$flash.Location=New-Object Drawing.Point(15,565);$form.Controls.Add($flash);$pass=New-Object Windows.Forms.Button;$pass.Text='Mark PASS and flash next';$pass.Location=New-Object Drawing.Point(150,565);$pass.Size=New-Object Drawing.Size(210,30);$pass.Enabled=$false;$form.Controls.Add($pass);$exit=New-Object Windows.Forms.Button;$exit.Text='Exit';$exit.Location=New-Object Drawing.Point(685,565);$form.Controls.Add($exit)
function Update-Display {$item=$Items[$script:CurrentIndex-1];$current.Text="Current: $($item.Index)/32 $($item.Artifact)";$list.Items.Clear();foreach($entry in $Items){$mark=if($script:Confirmed -contains $entry.Index){'[PASS]'}elseif($entry.Index -eq $script:CurrentIndex){'[CURRENT]'}else{'[WAIT]'};[void]$list.Items.Add("$mark $($entry.Index): $($entry.Artifact)")};$list.SelectedIndex=$script:CurrentIndex-1}
function Flash-Current {$chosen=$portBox.Text.Trim().ToUpperInvariant();if(-not(Test-Port $chosen)){[Windows.Forms.MessageBox]::Show('Port must be COM followed by digits.');return};$script:FlashVerified=$false;$pass.Enabled=$false;$item=$Items[$script:CurrentIndex-1];try{$result=Invoke-CurrentFlash $item $chosen $Gh $Python $Sha;$output.Text="Log: $($result.LogPath)`r`n$($result.Output)";if($result.Success){$script:FlashVerified=$true;$pass.Enabled=$true;$status.Text='Status: hash verified. Perform the manual runtime test, then mark PASS.'}else{$status.Text='Status: flash did not provide exit 0 and Hash of data verified.'}}catch{$output.Text=$_|Out-String;$status.Text='Status: error; item was not advanced.'}}
$flash.Add_Click({Flash-Current});$pass.Add_Click({if(-not $script:FlashVerified){return};$next=Get-NextProgress $script:CurrentIndex $script:Confirmed;$script:CurrentIndex=$next.CurrentIndex;$script:Confirmed=@($next.ConfirmedIndexes);$script:FlashVerified=$false;Save-State;Update-Display;$pass.Enabled=$false;if($next.Completed){$status.Text='Status: all 32 items were manually confirmed.'}else{Flash-Current}});$exit.Add_Click({$form.Close()});$list.Add_SelectedIndexChanged({if($list.SelectedIndex -ne ($script:CurrentIndex-1)){$list.SelectedIndex=$script:CurrentIndex-1}});Update-Display;[void]$form.ShowDialog()
